GoogleCloudPlatform/gce-automated-ad-join

register-computer/main.py

This is a workaround for https://github.com/googleapis/python-kms/issues/34,
which broke the use of positional arguments.

Use named arguments in decrypt() call

---

ad-joining/register-computer/kerberos/password.py

Write the krb5 configuration to a temporary file to avoid collisions in between calls to `ksetpwd`. This change can be treated independently from the efforts to move to GCR and should be merged with master.

Write krb5 configuration to temporary file

---

ad-joining/ksetpwd/ksetpwd.c
ad-joining/register-computer/kerberos/password.py
ad-joining/register-computer/main.py

Increase number and delay between retries to better deal with situations where DCs are temporarily out of sync. 
Cherry-picked d03a6725725c23fe0914287e8ab293f47f1c4bdc from `feature/gke`

Extend retries to accommodate DC synchronization delay

---

ad-joining/register-computer/join.ps1

Add-Computer attempted to show a prompt when using WINDOWS_LTSC, which caused an exception. Added -Force to not show the prompt

Fix - Add-Computer fails when running script in WINDOWS_LTSC images

---

ad-joining/register-computer/ad/domain.py

This PR removes trailing . from the response of the SRV record query locating domain controllers in the domain.

Remove trailing . in SRV record DNS query response

---

ad-joining/register-computer/kerberos/password.py

This PR fixes krb5.conf which contained illegal spaces/line breaks effectively rendering it ineffective. Additionally we prevent SRV lookups for the Kerberos realm and the KDC which may result in krb5 connecting to another domain controller than was initially used to create the computer account/group leading to replication issues and failures.

Fix krb5.conf

---

.gitignore

This PR will add `cloudbuild.hydrated.yaml` to ignored files.

Ignore hydrated cloudbuild.yaml

---

ad-joining/register-computer/join.ps1

This PR adds instrumentation to record a packet capture on the joining VM to analyze the traffic flow during the join operation. This feature is not by default enabled but can be individually enabled by setting `enable-adjoin-diagnostics` and `adjoin-diagnostics-bucket` metadata attributes.

Add packet capture diagnostics for join operation

---

ad-joining/register-computer/ad/domain.py
ad-joining/register-computer/join.ps1
ad-joining/register-computer/main.py

This PR changes the selection process for the DC against which the computer account creation and password reset operations are executed. On the VM that is to be joined to AD the closest site is determined and then passed to the join function which then will lookup a DC in the closest site.

Make DC selection site-aware

---

ad-joining/register-computer/main.py

Changed hash function from retuning 6 chars to 4 chars.
Resolving #36

Fix name shortening for non-MIG VMs

---

ad-joining/register-computer/main.py

This PR makes the ad_site argument in __connect_to_activdirectory optional which broke AD object cleanup. The function already handles an empty argument and ad_site should be optional.

Fixed AD object cleanup

---

ad-joining/README.md
ad-joining/register-computer/ad/domain.py
ad-joining/register-computer/main.py

This PR adds the capability to use LDAPS to Active Directory. LDAPS will be on by default but fallback to LDAP is automatic if a secure connection can't be established. Customers using private non-public Certification Authorities can upload their trust chain to secret manager to allow for server certificate verification.
This PR closes #41.

Enable LDAPS connections to Active Directory

---

ad-joining/README.md

Documentation specifies port 689 for LDAPS which is incorrect.

Fix wrong LDAPS port in documentation

---

ad-joining/register-computer/join.ps1
ad-joining/register-computer/main.py

This PR changes the behavior of the join script retrieved by the client in order to perform the domain join. The domain name, required for AD site-awareness will now be retrieved from the join service protected by authentication.

Retrieve domain name from join service

---

ad-joining/register-computer/kerberos/password.py
ad-joining/register-computer/main.py

This PR will remove the fixed usage of RC4 encryption type for TKT and TGS and allow [the defaults](https://web.mit.edu/kerberos/krb5-1.18/doc/admin/conf_files/krb5_conf.html#libdefaults) to take hold.

Remove fixed usage of RC4 encryption for TKT and TGS

---

ad-joining/register-computer/join.ps1
ad-joining/register-computer/main.py

In case the service (or load balancer/reverse proxy) in front of the service does not return JSON handle the error accordingly and provide proper output to the console.

Properly handle upstream errors

---

ad-joining/register-computer/ad/domain.py
ad-joining/register-computer/main.py

This PR increases the receive timeout for LDAP connections. Additionally, it add retry logic to group update functions for which Active Directory shows contention under heavy load.

LDAP connection tweaks

---

ad-joining/Dockerfile
ad-joining/register-computer/main.py

Python 3.7 will be [end of life in nine months](https://endoflife.date/python). This PR upgrades to Python 3.10 using the slim container base image.

Upgrade to Python 3.10

---

ad-joining/register-computer/main.py

Unlike other endpoints, the /cleanup endpoint isn't supposed to be called by GCE instances, but by Cloud Scheduler. Therefore, don't require the google claim to be present in the bearer token.

b/272022183 Don't require google claim for /cleanup

---

ad-joining/Dockerfile

When building the Docker image on Cloud Build, the operation
COPY --from=build-cc /lib/x86_64-linux-gnu/libcom_err.* /register-computer/kerberos/bin/
consistently fails. In other environments (such as Cloud Shell), the copy works fine.
To work around this issue, replace the wildcard copy by explicit file copies.

b/291096322 Avoid wildcards in COPY operation

---

ad-joining/cloudbuild.yaml

Deploy Cloud Run so that it uses direct VPC access instead of requiring a serverless VPC connector to be deployed.

Use direct VPC access

---

ad-joining/README.md
ad-joining/register-computer/gcp/project.py
ad-joining/register-computer/main.py

- Initialize client so that it sends a `User-Agent` header in all requests
- Use same client across all files

Set custom user agent in Compute Engine API requests

---

ad-joining/cloudbuild.yaml
ad-joining/register-computer/ad/domain.py
ad-joining/register-computer/gcp/project.py
ad-joining/register-computer/main.py

Extend cleanup logic so that it not only deletes the
computer object, but also the associated DNS record
Note: For DNS cleanup to work, the register-computer
account must be granted delete-access to the
respective container in Active Directory.

Clean up DNS records of stale computer accounts

---

ad-joining/register-computer/ad/domain.py
ad-joining/register-computer/main.py

Skip DNS record cleanup for computer accounts that
don't have a `dNSHostName`.
Fixes #96

Conditionally skip DNS record cleanup

---

ad-joining/register-computer/ad/domain.py
ad-joining/register-computer/main.py

Computer accounts can have children. Apply the
LDAP_SERVER_TREE_DELETE_OID control when deleting
computer accounts to ensure proper cleanup.
Cf #96

Perform recursive delete on stale computer accounts
